# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OP4mUWwt9bcoskyboJhbjIB8VArFVT2d
"""

import random

# List of branding words for innerwear
prefixes = ["Bison", "Ultra", "Flex", "Power", "Air", "Max"]
suffixes = ["Grip", "Weave", "Fit", "Comfort", "Shield", "Core"]

def generate_names(category, count=5):
    names = []
    for _ in range(count):
        name = f"{random.choice(prefixes)} {random.choice(suffixes)}"
        names.append(name)
    return names

# User input
category = input("Enter product category (e.g. sport innerwear, summer wear): ")
print("\nGenerated product names for:", category)
print("-" * 40)

for name in generate_names(category):
    print(name)